# Generated by Django 6.0 on 2025-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Job name')),
                ('description', models.CharField(max_length=200, verbose_name='Job rank')),
                ('banner', models.ImageField(upload_to='pages/photos', verbose_name='Job banner')),
                ('redirect', models.URLField(verbose_name='Job redirect link')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='pages/photos', verbose_name='Project banner')),
                ('name', models.CharField(max_length=50000, verbose_name='Project name')),
                ('description', models.TextField(max_length=500, verbose_name='Project description')),
                ('redirect', models.CharField(max_length=50000, verbose_name='Project url')),
            ],
        ),
    ]
